// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM-LFSIhLFRpKM63cWpJeWWJwdNQKcgqo',
    appId: '1:160977774494:web:2449ac00278a754122d88f',
    messagingSenderId: '160977774494',
    projectId: 'gotabang',
    authDomain: 'gotabang.firebaseapp.com',
    databaseURL: 'https://gotabang-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gotabang.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBejNem9IFWCaP4aHPYYKOTjY_aXHTtpsg',
    appId: '1:160977774494:android:f0fdf7cd9440afc522d88f',
    messagingSenderId: '160977774494',
    projectId: 'gotabang',
    databaseURL: 'https://gotabang-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gotabang.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcwE8UYzPj_RNtWmnFDd2SU3d4RhMT3Sk',
    appId: '1:160977774494:ios:7ba13d97c23e7f1522d88f',
    messagingSenderId: '160977774494',
    projectId: 'gotabang',
    databaseURL: 'https://gotabang-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gotabang.appspot.com',
    iosClientId: '160977774494-57hp128q0hfhrocpd78j2rhdkgjv602b.apps.googleusercontent.com',
    iosBundleId: 'com.example.gotabangMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcwE8UYzPj_RNtWmnFDd2SU3d4RhMT3Sk',
    appId: '1:160977774494:ios:7ba13d97c23e7f1522d88f',
    messagingSenderId: '160977774494',
    projectId: 'gotabang',
    databaseURL: 'https://gotabang-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gotabang.appspot.com',
    iosClientId: '160977774494-57hp128q0hfhrocpd78j2rhdkgjv602b.apps.googleusercontent.com',
    iosBundleId: 'com.example.gotabangMobile',
  );
}
